### ISSUE TITLE
Does This Convert Local Phone Number to International Formatted Number Based on Locale?

### ISSUE THREAD

**Issue by Jayvd** [dartsidedev/whatsapp_unilink#1]
Does This Convert Local Phone Number to International Formatted Number Based on Device's Locale?

Thank you

**Comment by vincevargadev** [comment]
Hey @Jayvd!

No, this package does not convert from local to international format, that's up to the user of the package, meaning it's up to you to make that conversion before you call the `whatsapp_unilink` package. I find that that is outside of the scope of the package.

The package removes all non-digits from the phone number and removes the leading zero(s). That covers the cases where the user might enter `00` instead of `+`, but the package does not try to automatically figure out the country code of the user based on the locale. For more info see the regexes here: https://github.com/dartsidedev/whatsapp_unilink/blob/master/lib/src/whatsapp_unilink_base.dart#L31
